### ISSUE TITLE
关于TargetAware的实现

### ISSUE THREAD

**Issue by kongbia** [ohhhyeahhh/SiamGAT#3]
请问关于targetaware中将目标框映射到特征图大小上的
```roi = torch.round((bbox + 1 - offset + stride / 2) / stride - 1).int()```
这行代码可以解释为什么是这样操作吗

**Comment by twotwo2** [comment]
参考[iccv2015_tutorial_convolutional_feature_maps_kaiminghe](http://kaiminghe.com/iccv15tutorial/iccv2015_tutorial_convolutional_feature_maps_kaiminghe.pdf)和《Spatial Pyramid Pooling in Deep Convolutional Networks for Visual Recognition》。
