### ISSUE TITLE
Training the problem

### ISSUE THREAD

**Issue by 6imust** [ohhhyeahhh/SiamGAT#33]
Hello, I would like to ask how to solve the following problem encountered in the training  

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe1 in position 755: ordinal not in range(128)

**Comment by Capricorn231** [comment]
Please provide us with the complete error message and related error codes. Based on the above information, we cannot locate the problem.

**Comment by 6imust** [comment]
Hello, data sets and processed data sets are not in the code&nbsp; &nbsp;The specific errors are as follows&nbsp;&nbsp;


(GAT) ***@***.***:/workspace/SiamGAT-main/tools# python3 train.py
[2022-03-15 00:55:47,136-rk0-train.py#271] init done
Traceback (most recent call last):
&nbsp; File "train.py", line 332, in <module&gt;
&nbsp; &nbsp; main()
&nbsp; File "train.py", line 274, in main
&nbsp; &nbsp; cfg.merge_from_file(args.cfg)
&nbsp; File "/root/anaconda3/envs/GAT/lib/python3.6/site-packages/yacs/config.py", line 212, in merge_from_file
&nbsp; &nbsp; cfg = self.load_cfg(f)
&nbsp; File "/root/anaconda3/envs/GAT/lib/python3.6/site-packages/yacs/config.py", line 363, in load_cfg
&nbsp; &nbsp; return cls._load_cfg_from_file(cfg_file_obj_or_str)
&nbsp; File "/root/anaconda3/envs/GAT/lib/python3.6/site-packages/yacs/config.py", line 372, in _load_cfg_from_file
&nbsp; &nbsp; return cls._load_cfg_from_yaml_str(file_obj.read())
&nbsp; File "/root/anaconda3/envs/GAT/lib/python3.6/encodings/ascii.py", line 26, in decode
&nbsp; &nbsp; return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe1 in position 755: ordinal not in [`range(128)`]



thank you very much for your help




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ohhhyeahhh/SiamGAT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月14日(星期一) 下午3:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ohhhyeahhh/SiamGAT] Training the problem (Issue #33)





 
Please provide us with the complete error message and related error codes. Based on the above information, we cannot locate the problem.
  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;
 

从QQ邮箱发来的超大附件

SiamGAT.zip (112.59M, 2022年04月14日 09:22 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=793664619fb197cd76d554071e31531a5d5206585c00580614555057091c55020c5749000b0005180f5701555e0400030d570105383a61665057092679654f4f5046645c&code=96da81a5

**Comment by 6imust** [comment]
Hello, data sets and processed data sets are not in the code   The specific errors are as follows  

(GAT) root@19aeae92d876:/workspace/SiamGAT-main/tools# python3 train.py
[2022-03-15 00:55:47,136-rk0-train.py#271] init done
Traceback (most recent call last):
  File "train.py", line 332, in <module>
    main()
  File "train.py", line 274, in main
    cfg.merge_from_file(args.cfg)
  File "/root/anaconda3/envs/GAT/lib/python3.6/site-packages/yacs/config.py", line 212, in merge_from_file
    cfg = self.load_cfg(f)
  File "/root/anaconda3/envs/GAT/lib/python3.6/site-packages/yacs/config.py", line 363, in load_cfg
    return cls._load_cfg_from_file(cfg_file_obj_or_str)
  File "/root/anaconda3/envs/GAT/lib/python3.6/site-packages/yacs/config.py", line 372, in _load_cfg_from_file
    return cls._load_cfg_from_yaml_str(file_obj.read())
  File "/root/anaconda3/envs/GAT/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe1 in position 755: ordinal not in [[`range(128)`])]
