### ISSUE TITLE
How long is SiamGAT model training?

### ISSUE THREAD

**Issue by Soarkey** [ohhhyeahhh/SiamGAT#35]
Hi, I want to use 4 GTX-1080Ti cards to retrain this model.
Before that, I would like to ask the approximate training time of the model.
Thanks!

**Comment by longcoolman** [comment]
may i ask you how to run de model,can you help me?
wechat: sunny827484930

**Comment by twotwo2** [comment]
It may take about 24 hours. The exact training time is related to the speed of data reading. With hardware support, try increasing the $__C.TRAIN.NUM_WORKERS$ value to see if the training speed is faster.

**Comment by longcoolman** [comment]
much thank you for your help!
















At 2022-05-12 11:50:33, "twotwo2" ***@***.***> wrote:

It may take about 24 hours. The exact training time is related to the speed of data reading. With hardware support, try increasing the $__C.TRAIN.NUM_WORKERS$ value to see if the training speed is faster.
