### ISSUE TITLE
关于GOT测试和训练的问题

### ISSUE THREAD

**Issue by ghostbreaken** [ohhhyeahhh/SiamGAT#38]
作者你好，关于got，我只用got训练，并用的是experiments/siamgat_googlenet_got10k的config.yaml, 有关三个参数取值也和代码一样，最高的AO只有0.597，远达不到论文精度，请问还需要怎么调整嘛？

**Comment by kun-dragon** [comment]
作者你好，我也是用的提供的config.yaml训练的，测试结果远不及论文结果，是什么参数有问题吗？

**Comment by twotwo2** [comment]
config中给定的三个参数跟我们训练的模型适配，新训练的模型可能需要微调下三个参数才能获得较好的结果。

**Comment by hongtaofly** [comment]
大家好，请问在训练lasot版本时，使用module_builer_gat更好还是使用module_buider_gat_got呢
