### ISSUE TITLE
test on got10k

### ISSUE THREAD

**Issue by aaahuia** [ohhhyeahhh/SiamGAT#8]
I test on got10k with got10k_model.pth, siamgat_googlenet_got10k, and __C.HP_SEARCH.GOT10k = [0.7, 0.02, 0.35]
but my result is 60.2  71.7 46.7, not 62.7 74.3 48.8.
How do I set the parameters, or what is wrong with me?

**Comment by twotwo2** [comment]
The parameters are true, maybe you have some small mistakes.

**Comment by DXZDXZ** [comment]
@aaahuia I have the same problem. Have you solved it?

**Comment by aaahuia** [comment]
> @aaahuia I have the same problem. Have you solved it?

No

**Comment by yingxin666** [comment]
I run the train.py twice on got-10k datasets,but my result is 0.594 0.697 0.453 and 0.592 0.702 0.462

**Comment by yingxin666** [comment]
@DXZDXZ  @aaahuia @twotwo2  Have you sloved this problem?
