### ISSUE TITLE
pre trained models on Baidu

### ISSUE THREAD

**Issue by Gal147** [ohhhyeahhh/SiamGAT#9]
Hi Guys, thanks for your work.
Can you please upload the pre-trained models to a site that doesn't require a china phone number?
would be happy to test them but I can't download them from Baidu

**Comment by ohhhyeahhh** [comment]
> Hi Guys, thanks for your work.
> Can you please upload the pre-trained models to a site that doesn't require a china phone number?
> would be happy to test them but I can't download them from Baidu

Hi, please find the new links from the updated readme file.
